import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Vanisutra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" />
      </head>
      <body className={`antialiased bg-white font-customFont`}>{children}</body>
    </html>
  );
}
